export const CLASSES = 
[
    { id: 1, name: "Berserker (BT)", default_role: "DPS" },
    { id: 2, name: "Berserker (Mayhem)", default_role: "DPS" },
    { id: 3, name: "Destroyer (GT)", default_role: "DPS" },
    { id: 4, name: "Destroyer (RH)", default_role: "DPS" },
    { id: 5, name: "Gunlancer (Blue)", default_role: "DPS" },
    { id: 6, name: "Gunlancer (Red)", default_role: "DPS" },
    { id: 7, name: "Slayer (Predator)", default_role: "DPS" },
    { id: 8, name: "Slayer (Punisher)", default_role: "DPS" },
    { id: 9, name: "Arcanist (Emperor)", default_role: "DPS" },
    { id: 10, name: "Arcanist (Empress)", default_role: "DPS" },
    { id: 11, name: "Sorceress (Igniter)", default_role: "DPS" },
    { id: 12, name: "Sorceress (Reflux)", default_role: "DPS" },
    { id: 13, name: "Summoner (CO)", default_role: "DPS" },
    { id: 14, name: "Summoner (Master)", default_role: "DPS" },
    { id: 15, name: "Glaivier (Control)", default_role: "DPS" },
    { id: 16, name: "Glaivier (Pinnacle)", default_role: "DPS" },
    { id: 17, name: "Scrapper (Taijutsu)", default_role: "DPS" },
    { id: 18, name: "Scrapper (Shock)", default_role: "DPS" },
    { id: 19, name: "Soulfist (EO)", default_role: "DPS" },
    { id: 20, name: "Soulfist (RS)", default_role: "DPS" },
    { id: 21, name: "Wardancer (ESO)", default_role: "DPS" },
    { id: 22, name: "Wardancer (FI)", default_role: "DPS" },
    { id: 23, name: "Striker (Deathblow)", default_role: "DPS" },
    { id: 24, name: "Striker (ESO)", default_role: "DPS" },
    { id: 25, name: "Breaker (Asura)", default_role: "DPS" },
    { id: 26, name: "Breaker (BK)", default_role: "DPS" },
    { id: 27, name: "Artillerist (FPE)", default_role: "DPS" },
    { id: 28, name: "Artillerist (Barrage)", default_role: "DPS" },
    { id: 29, name: "Deadeye (Pistoleer)", default_role: "DPS" },
    { id: 30, name: "Deadeye (EW)", default_role: "DPS" },
    { id: 31, name: "Gunslinger (PM)", default_role: "DPS" },
    { id: 32, name: "Gunslinger (TTH)", default_role: "DPS" },
    { id: 33, name: "Machinist (EVO)", default_role: "DPS" },
    { id: 34, name: "Machinist (AT)", default_role: "DPS" },
    { id: 35, name: "Sharpshooter (DS)", default_role: "DPS" },
    { id: 36, name: "Sharpshooter (LC)", default_role: "DPS" },
    { id: 37, name: "Deathblade (RE)", default_role: "DPS" },
    { id: 38, name: "Deathblade (Surge)", default_role: "DPS" },
    { id: 39, name: "Reaper (Lunar)", default_role: "DPS" },
    { id: 40, name: "Reaper (Hunger)", default_role: "DPS" },
    { id: 41, name: "Shadowhunter (DI)", default_role: "DPS" },
    { id: 42, name: "Shadowhunter (PS)", default_role: "DPS" },
    { id: 43, name: "Souleater (Full Moon)", default_role: "DPS" },
    { id: 44, name: "Souleater (Night's Edge)", default_role: "DPS" },
    { id: 45, name: "Aeromancer (Drizzle)", default_role: "DPS" },
    { id: 46, name: "Aeromancer (Windfury)", default_role: "DPS" },
    { id: 47, name: "Artist", default_role: "Support" },
    { id: 48, name: "Bard", default_role: "Support" },
    { id: 49, name: "Paladin", default_role: "Support" }
]


export const RAIDS = [
    { id: 1, name: "Aegir Normal", min_item_level: 1660 },
    { id: 2, name: "Aegir Hard", min_item_level: 1680 }
];
